Updated help dialogs and caught a few input-checking errors

diff --git a/forbesread b/forbesread
--- a/forbesread
+++ b/forbesread
@@ -22,16 +22,16 @@ data_regex='>[0-9]{1,2}\.'
 
 # Help message dialog
 # -------------------
+helpstr="forbesread - A script for quickly reading single-fact,"
+helpstr+=" multi-page Forbes lists.\n\n"
+helpstr+="usage: forbesread <url> [numpages]\n"
+helpstr+="\tExample URL:\n\thttp://www3.forbes.com/leadership/"
+helpstr+="the-25-most-underpaid-jobs-in-america/\n\n"
+helpstr+="\tnumpages: (optional) number of pages in the list\n"
+helpstr+="\t          (defaults to attempting to get numpages from URL)\n"
 function helpmsg
 {
-    printf "forbesread - A script for quickly reading single-fact,"
-    printf " multi-page Forbes lists.\n\n"
-    printf "USAGE: ./forbesread <url> [numpages]\n\n"
-    printf "Example URL: http://www3.forbes.com/leadership/"
-    printf "the-25-most-underpaid-jobs-in-america/\n\n"
-    printf "numpages:    optional INT in case the number of pages"
-    printf " isn't immediately apparent from the URL\n\n"
-
+    printf "$helpstr" 1>&2
 }
 
 # Check if number is integer func
@@ -42,15 +42,13 @@ function isint
 {
     if [ $# -ne 1 ]
     then
-        echo "ERROR: function isint was given incorrect number of arguments"
-        helpmsg
+        echo "Error: isint was given incorrect number of arguments" 1>&2
         exit 1
     fi
 
-    local clean_num=$(tr --delete '[:space:]' <<< "$1")  # remove all whitespace
-    local test_num=$(grep $grep_args "[0-9]{1,}" <<< "$clean_num")
+    local clean_num=$(tr --delete '[:space:]' <<< "$1")  # del whitespace
 
-    if [ -n "$test_num" ]
+    if grep $grep_args "[0-9]{1,}" <<< "$clean_num"
     then
         return 0
     else
@@ -63,14 +61,13 @@ function isint
 
 # Number of args check
 # --------------------
-if [ $# -lt 1 ] && [ $# -gt 2 ]
+if [ $# -lt 1 ] || [ $# -gt 2 ]
 then
-    printf "ERROR: incorrect number of args\n\n"
+    printf "Error: incorrect number of args\n" 1>&2
     helpmsg
     exit 1
 fi
 
-echo "args checked"
 
 # Help dialog check
 # -----------------
@@ -81,8 +78,6 @@ then
 else
     url="$1"
 fi
-
-echo "help checked"
 
 # Finding number of pages in url
 # ------------------------------
@@ -111,12 +106,12 @@ then
     # If error, give user 1 chance to enter the correct number
     # Only give 1 chance because the person using this would probably
     # rather restart the program than deal with a loop
-    printf "ERROR: URL did not have a recognizable number of pages\n\n"
+    printf "Error: URL did not have a recognizable number of pages\n\n"
     read -p "Please enter the number of pages instead: " num
     # Catch bad input
     if ! [ $(grep -wE "[0-9]{1,}" <<< "$num") ]
     then
-        printf "\n\nERROR: did not recognize an integer number\n\n"
+        printf "\n\nError: did not recognize an integer number\n\n"
         printf "given url: $url\n\n"
         helpmsg
         exit 1
diff --git a/netcheck b/netcheck
--- a/netcheck
+++ b/netcheck
@@ -12,44 +12,62 @@
 set -o errexit  # exit on any command error
 
 # Displays usage/help dialog
+helpstr="usage: netcheck [-n num] [-q]\n"
+helpstr+="\t-n num: how many times to ping 8.8.8.8\n"
+helpstr+="\t        (default num is 5)\n\n"
+helpstr+="\t-q:     enables quiet mode\n" 
+helpstr+="\t        (default is loud)\n"
 function helpmsg
 {
-    printf "Convenience wrapper of ping for checking"
-    printf " my Internet connection.\n"
-    printf "Usage: netcheck [num_pings] [-q]\n"
-    printf "\tnum_pings controls how many times to ping 8.8.8.8\n"
-    printf "\t\"-q\" enables quiet mode\n"
-    printf "\nIf no args given, executes \"ping -c5 8.8.8.8\n"
+    printf "$helpstr" 1>&2
 }
 
 # Input Arg Parsing -------------------------------------------------
 
 # too many args check
-if [ $# -gt 2 ]
+if [ $# -gt 3 ]
 then
+    printf "Error: too many arguments\n" 1>&2
     helpmsg
     exit 1
-# help dialog check
-elif [ "$1" = "-h" ] || [ "$1" = "--help" ]
+fi
+
+# long help cmd check
+if [ $1 = "--help" ]
 then
     helpmsg
     exit 0
 fi
 
-# parsing the input args in arbitrary order
-for i in "$@"
+# optional arg parsing
+OPTIND=1  # reset getopts just in case
+while getopts "h?qn:" opt
 do
-    if [ "$i" = "-q" ]
-    then
+    case "$opt" in
+    h|\?)
+        helpmsg
+        exit 0
+        ;;
+    n)
+        num_pings="$OPTARG"
+        ;;
+    q)
         loud_flag=false
-    elif [[ $i =~ ^[1-9][0-9]*$ ]]
-    then
-        num_pings=$i  # no quotes; i must be INT
-    else
+        ;;
+    *)
+        printf "Error: unrecognized option\n" 1>&2
         helpmsg
         exit 1
-    fi
+    esac
 done
+
+# make sure num_pings is an int
+if ! grep --extended-regexp --quiet "^[1-9][0-9]*$" <<< "$num_pings"
+then
+    printf "Error: num (value: $num_pings) is not an integer\n" 1>&2
+    helpmsg
+    exit 1
+fi
 
 # param expansion for defaults
 : ${num_pings:=5}
